CREATE TABLE [dbo].[FileStore] (
    [Id]       INT NOT NULL IDENTITY(1,1),
    [UniqueId] UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL CONSTRAINT [DF_FileStore_UniqueId] DEFAULT NEWID(),
    [FileData] VARBINARY (MAX) FILESTREAM NOT NULL,
    CONSTRAINT [PK_FileStore] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [AK_FileStore_UniqueId] UNIQUE NONCLUSTERED ([UniqueId] ASC),
) FILESTREAM_ON [QuickFileFileStreamGroup];

